### ISSUE TITLE
firefox vs chrome

### ISSUE THREAD

**Issue by icf20** [freenas/gui#24]
hello, i am testing the FreeNAS-10-MASTER-201604140930 build and i notice that some GUI options are out of place when using firefox but now when i am using chromium.

is this because firefox itself or because the freenas gui

**Comment by joshuarule** [comment]
This is likely due to css vendor prefixes not yet being added to all of the properties. We haven't done any extensive cross browser testing so there are likely some bugs. It is both because of the freenas gui and because of how different browsers handle css. We will work to support current browsers.
